sonar.projectKey=evo-foundation-models-ai-development-workshop
sonar.projectName=AI Development workshop
sonar.projectVersion=0.0.1
# Disable code coverage monitoring
sonar.coverage.exclusions=**/*
sonar.coverage.jacoco.xmlReportPaths=
sonar.coverage.jacoco.htmlReportPaths=
sonar.coverage.jacoco.itReportPaths=
sonar.coverage.jacoco.overallReportPaths=
